name: "AssetStudio"
on: [push]
jobs:
  Build-Artifact:
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Building application"
        uses: microsoft/setup-msbuild@v1.0.2
