name: "AssetStudio"
on: [push]
jobs:
  Build-Artifact:
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "Downloading FBXSDK"
        run: Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-0-1/fbx202001_fbxsdk_vs2017_win.exe" -OutFile fbxsdk.exe
        
      - name: "Add msbuild to PATH"
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: "Add nuGET to PATH"
        uses: nuget/setup-nuget@v1
      
      - name: "Building artifact"
        run: |
          echo "${{ github.workspace }}"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          nuget restore
          msbuild AssetStudio.sln /verbosity:minimal /p:Configuration=Release /p:Platform="Any CPU" /p:AllowedReferenceRelatedFileExtensions=".pdb"
      
      - name: "Archiving artifact"
        run: Compress-Archive -Path "${{ github.workspace }}\AssetStudioGUI\bin\Release" -DestinationPath "${{ github.workspace }}\AssetStudio.zip"
        
      - name: "Uploading artifacts"
        uses: actions/upload-artifact@v2
        with:
          path: "${{ github.workspace }}/AssetStudio.zip"
